name: Update README

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@master
      - name: Recent GitHub Activity - Profile Readme
        uses: Readme-Workflows/recent-activity@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}